#spring:
#  profiles:
#    active: dev
#
#  # config datasource
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://8.131.86.82:3306/xdj_robot?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    # connect pool default hikari
#    hikari:
#      #      connection-init-sql: select xdjrobot from dual
#      maximum-pool-size: 4
#      minimum-idle: 2
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#    serialization:
#      write-dates-as-timestamps: false
#  # nacos 配置中心地址
#  cloud:
#    nacos:
#      server-addr: 42.192.207.31:8848